---
collections:
  - name: community.aws
  - name: awx.awx
  - name: amazon.aws
    version: >=3.1.1
  - name: ansible.posix
  - name: ansible.product_demos
  - name: ansible.windows
  - name: chocolatey.chocolatey
  - name: community.crypto
  - name: community.general
  - name: community.mysql
  - name: community.windows
  - name: f5networks.f5_modules
  - name: redhat_cop.controller_configuration
  - name: redhat_cop.tower_utilities
  - name: containers.podman
  - name: ansible.network
