---
################### Get workshop nodes info ###################

- name: grab facts for Gitlab
  amazon.aws.ec2_instance_info:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      "tag:Workshop_gitlab": "{{ec2_name_prefix}}-gitlab"
  register: gitlab_node_facts

################### Create inventories ###################

- name: GitLab | Add new instance to host group
  add_host:
    hostname: 'gitlab'
    short_name: "{{ item.tags.short_name }}"
    username: "{{ item.tags.username }}"
    ansible_user: "{{ item.tags.username }}"
    ansible_ssh_private_key_file: "{{ playbook_dir }}/{{ ec2_name_prefix }}/{{ ec2_name_prefix }}-private.pem"
    ansible_host: "{{ item.public_ip_address }}"
    private_ip: "{{ item.private_ip_address }}"
    groups:
      - rhel
      - gitlab
  with_items: "{{ gitlab_node_facts.instances }}"
