---
- name: configure SNMP
  hosts: cisco
  gather_facts: false

  tasks:

    - name: Override commands with provided configuration
      cisco.ios.snmp_server:
        config:
          location: 'Durham'
          packet_size: 500
          communities:
            - acl_v4: acl_uq
              name: Durham-community
              rw: true
