---
- name: upgrade pip (F5 MODE)
  become: true
  pip:
    name: pip
    state: latest

- name: upgrade setuptools to 44 (F5 MODE)
  become: true
  pip:
    name: setuptools==44.0.0

- name: install f5 workshop dependicies (F5 MODE)
  become: true
  pip:
    name:
      - netaddr
      - jmespath
      - lxml
      - ipaddr
    state: latest

- name: install f5 collection
  become_user: "{{ username }}"
  shell: "ansible-galaxy collection install {{ item }} --force-with-deps "
  register: f5networks
  loop:
    - f5networks.f5_modules
    - community.docker
  until: f5networks is not failed
  retries: 5

# sean removed on 9/30/2021... this does not exist
# - name: Pull an extra image for f5
#   become_user: "{{ loop_item }}"
#   containers.podman.podman_image:
#     name: "quay.io/acme_corp/f5_modules:latest"
#   loop:
#     - "{{ username }}"
#     - awx
#   loop_control:
#     loop_var: loop_item
