---
## Craig Brandt
# @todo @craig-br This is the worst hack in recorded history. Fix security workshop EE usage
- name: Overwrite standard ansible-navigator.yml for security
  template:
    src: security-ansible-navigator.yml.j2
    dest: "/home/{{ username }}/.ansible-navigator.yml"
    owner: "{{ username }}"
    group: "{{ username }}"
