---
- name: SSL cert block
  block:
    - name: tower vs controller start
      block:
        - name: tower start
          include_tasks: "tower_start.yml"
      rescue:
        - name: controller start
          include_tasks: "controller_start.yml"

    # directions found here https://certbot.eff.org/lets-encrypt/centosrhel8-other
    - name: install certbot if not already installed
      dnf:
        name: certbot
        state: present
        disable_gpg_check: true

    - &tower-pinger-block
      block:
        - name: check Tower status
          shell: "curl --user 'admin:{{ admin_password }}' -vkL -XGET https://localhost/api/v2/ping/"
          register: check2
        - name: Display /api/v2/ping results (stdout)
          debug:
            msg: '{{ check2.stdout }}'
        - name: Display /api/v2/ping results (stderr)
          debug:
            msg: '{{ check2.stderr }}'

    - name: change ansible tower base URL
      block:
        - &tower-baseurl-task
          awx.awx.tower_settings:
            name: TOWER_URL_BASE
            value: "https://{{ dns_name }}"
            tower_verify_ssl: false
            tower_host: https://localhost/
            tower_username: admin
            tower_password: "{{ admin_password }}"
          register: change_base_url
          until: change_base_url is not failed
          # tower may not be fully up yet, wait for it gratuitously
          retries: 12
          delay: 5
      rescue:
        - name: tower vs controller restart
          block:
            - name: tower restart
              include_tasks: "tower_restart.yml"
          rescue:
            - name: controller stop
              include_tasks: "controller_restart.yml"

        - *tower-pinger-block

        - <<: *tower-baseurl-task
          name: Run failed task again

    - name: tower vs controller stop
      block:
        - name: tower stop
          include_tasks: "tower_stop.yml"
      rescue:
        - name: controller stop
          include_tasks: "controller_stop.yml"

    # If this fails check out status of certbot: https://letsencrypt.status.io/
    - name: ISSUE CERT
      shell: certbot certonly --no-bootstrap --standalone -d {{ dns_name }} --email ansible-network@redhat.com --noninteractive --agree-tos
      register: issue_cert
      until: issue_cert is not failed
      retries: 5

    - name: Move SSL Key
      copy:
        remote_src: true
        src: "/etc/letsencrypt/live/{{ dns_name }}/privkey.pem"
        dest: /etc/tower/tower.key

    - name: Retrieve Specific SSL Cert
      slurp:
        src: "/etc/letsencrypt/live/{{ dns_name }}/cert.pem"
      register: intermediate_cert

    - name: Combine Specific and intermediate Cert
      template:
        src: combined_cert.j2
        dest: /etc/tower/tower.cert
  rescue:
    - name: no SSL cert for Automation Controller
      debug:
        msg: "SSL cert problem - no cert applied"
  always:
    # Turn on Ansible Controller if successful
    - name: tower vs controller start
      block:
        - name: tower start
          include_tasks: "tower_start.yml"
      rescue:
        - name: controller start
          include_tasks: "controller_start.yml"
