---
- name: editor block - update nginx configuration to support code server
  blockinfile:
    block: "{{ lookup('template', 'nginx_instruqt.conf') }}"
    dest: /etc/nginx/conf.d/automation-controller.nginx.conf
    insertbefore: "location / "

# Make sure we can re-run the automation platform installer during a lab without killing code-server access
- name: update Ansible installer nginx configuration template to support code server
  blockinfile:
    block: "{{ lookup('template', 'nginx_instruqt.conf') }}"
    dest: "{{ aap_dir }}/collections/ansible_collections/ansible/automation_platform_installer/roles/automationcontroller/templates/automation-controller.nginx.conf.j2"
    insertbefore: "location / "

- name: Replace add_header X-Frame-Options DENY with CSP frame-ancestors self in automation-controller.nginx.conf
  ansible.builtin.lineinfile:
    path: /etc/nginx/conf.d/automation-controller.nginx.conf
    regexp: '^(.*)add_header X-Frame-Options \"DENY\"\;'
    line: >-
      \1add_header Content-Security-Policy "frame-ancestors 'self';";
    backrefs: yes
    owner: root
    group: root
    mode: '0644'
  register: add_header_csp
  retries: 10
  until: add_header_csp is not changed

- name: Apply our systemd service file (instead of RPM file)
  ansible.builtin.template:
    src: code-server.service.j2
    dest: /etc/systemd/system/code-server.service
    owner: "{{ username }}"
    group: wheel
    mode: '0744'

- name: daemon-reload, enable and start code-server
  ansible.builtin.systemd:
    name: code-server
    enabled: true
    state: restarted
    daemon_reload: true
