---
- name: check if aap.tar.gz exists
  ansible.builtin.stat:
    path: "{{ playbook_dir }}/aap.tar.gz"
    checksum_algorithm: sha256
  register: stat_var

- name: attempt to download specified AAP
  block:
    - name: setup control node for workshop type
      include_tasks: 10_download.yml
  when: not stat_var.stat.exists or (stat_var.stat.exists and (stat_var.stat.checksum != provided_sha_value))

  rescue:
    - name: aap_download role has entered rescue stanza
      debug:
        msg: "download from access.redhat.com has failed, attempting to see if there is a cached aap.tar.gz file"

    - name: fail if file aap.tar.gz not found
      fail:
        msg: "This host has already had this playbook run against it"
      when: not stat_var.stat.exists
