---
- name: use COP controller_configuration collection
  when: controller_projects is defined
  vars:
    controller_validate_certs: false
    controller_hostname: "https://{{ ansible_host }}"
    controller_username: "admin"
    controller_password: "{{ admin_password }}"
  include_role:
    name: '{{ setup_controller }}'
  loop:
    - 'redhat_cop.controller_configuration.hosts'
    - 'redhat_cop.controller_configuration.organizations'
    - 'redhat_cop.controller_configuration.teams'
    - 'redhat_cop.controller_configuration.users'
    - 'redhat_cop.controller_configuration.projects'
    - 'redhat_cop.controller_configuration.job_templates'
    - 'redhat_cop.controller_configuration.roles'
  loop_control:
    loop_var: setup_controller
