---
- name: Teardown attendance
  include_tasks: teardown.yml
  when: teardown|bool

- name: setup DNS specific information
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{role_path}}/tasks/{{ dns_type }}.yml"
    - "{{role_path}}/tasks/none.yml"
  when: not teardown

- name: Configure attendance host
  import_tasks: attendance.yml
  when: not teardown
