---
- name: common workshop setup for control node
  include_tasks: "all_workshop.yml"
  when: workshop_type is defined

# we need a collection to be present on the control node

- name: install necessary collections
  become_user: "{{ username }}"
  shell: "ansible-galaxy collection install {{ item }} --force-with-deps "
  register: controlcollections
  loop:
    - community.general
    - ansible.posix
  until: controlcollections is not failed
  retries: 5

- name: check to see if automation controller is already up and running
  uri:
    url: https://localhost/api/v2/ping/
    method: GET
    user: admin
    password: "{{ admin_password }}"
    validate_certs: false
    force_basic_auth: true
  register: check_controller
  ignore_errors: true
  failed_when: false
  when:
    - controllerinstall is defined
    - controllerinstall|bool

- name: install controller if knob is set
  include_tasks: "controller.yml"
  when:
    - controllerinstall is defined
    - controllerinstall|bool
    - check_controller.status != 200

- name: Setup Route53 update service
  include_tasks: "route53_update.yml"
  when: tower_node_aws_api_access|default(false)|bool
